DROP TABLE IF EXISTS messages;
CREATE TABLE messages (
  id SERIAL PRIMARY KEY,
  type CHARACTER VARYING(255) NOT NULL,
  time TIMESTAMP WITH TIME ZONE NOT NULL,
  text CHARACTER VARYING(255) NOT NULL,
  payload JSON NOT NULL
);

DROP INDEX IF EXISTS messages_time;
CREATE INDEX messages_time ON messages (time);
